Feat/#59 art work 작품경매
ArtStroyage/ArtStoryage_Server pull request #60
Opened 2024-05-28 12:06 UTC by citycozy

# 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [x] 기타 사소한 수정

# ❗️ 관련 이슈 링크
Close #59 

# 📌 개요
- 경매 시작
- 경매 취소
- 입찰

# 🔁 변경 사항
## 기능 1

# 👀 기타 더 이야기해볼 점
입찰 최적화
# ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-05-28 12:34 UTC, SIWON990327 requested changes

2024-05-28 12:34 UTC, SIWON990327 commented on src/main/java/com/example/artstoryage/controller/ArtWorkController.java
> +  public BaseResponse<ArtWorkResponse> BidAuctionArtwork(
BidAuctionArtwork -> bidAuctionArtwork

2024-05-28 12:34 UTC, SIWON990327 commented on src/main/java/com/example/artstoryage/converter/ArtWorkConverter.java
> +  public static List<ArtWorkResponseDto.ArtWorksResponse> toArtWorksResponseList(
ArtWorkResponseDto 제거

2024-05-28 12:34 UTC, SIWON990327 commented on src/main/java/com/example/artstoryage/converter/ArtWorkConverter.java
> +
artWorkList.stream()
        .map(artWork -> ArtWorksResponse.builder()
            .artWorkId(artWork.getId())
            .title(artWork.getTitle())
            .build())
        .collect(Collectors.toList());
        
  이렇게 stream을 쓰면 코드가 간결해집니

2024-05-28 12:34 UTC, SIWON990327 commented on src/main/java/com/example/artstoryage/converter/ArtWorkConverter.java
> +  }
두 매서드가 중복되는데 toArtWorkResponse로 통일해도 되지 않을까요?

2024-05-28 12:34 UTC, SIWON990327 commented on src/main/java/com/example/artstoryage/domain/ArtWork.java
> +    auctionStartPrice = request.getBidPrice();
controller
클라이언트로부터의 요청을 받습니다.
AOP 등을 사용한 검증, 비즈니스 로직 처리 등을 서비스에게 위임합니다.
서비스가 처리한  결과를 받아 적절한 형태(DTO)로 변환해 응답합니다.
service
컨트롤러부터 DTO를 받아 검증, 데이터 작업 등의 비즈니스 로직을 수행합니다.
조작한 데이터를 저장하기 위해 repository, dao 등에게 해당 작업을 위임합니다.
처리 결과를 엔티티 클래스 또는 DTO 형태로 반환합니다 (저는 엔티티를 반환하는 걸 선호합니다)
repository
데이터를 저장합니다.
converter
클래스간 데이터 변환을 담당합니다.
주로 DTO, Entity간 변환을 수행합니다. (Reqeust DTO -> Entity, Entity -> Response DTO)

이런 흐름으로 가는데 bidAuctionArtWork는 Converter로 가도 되지 않을까요?

2024-05-28 12:34 UTC, SIWON990327 commented on src/main/java/com/example/artstoryage/service/impl/ArtWorkCommandServiceImpl.java
> +      throw new IllegalArgumentException("입찰가의 단위는 1만원입니다.");
일관성 있게 ArtWorkException으로 바꾸는건 어떨까요

2024-05-28 12:37 UTC, SIWON990327 commented
Assignees는 담당자 본인으로 설정

2024-05-28 16:49 UTC, citycozy commented on src/main/java/com/example/artstoryage/controller/ArtWorkController.java
> +  public BaseResponse<ArtWorkResponse> BidAuctionArtwork(
수정 완

2024-05-28 16:53 UTC, citycozy commented on src/main/java/com/example/artstoryage/converter/ArtWorkConverter.java
> +
toArtWorksResponseList 는 사용되지 않아서 충돌 수정했을 때 삭제했습니다.

stream👍👍👍
다른 list 메서드를 stream 사용하게 수정했습니다.

2024-05-28 17:04 UTC, citycozy commented on src/main/java/com/example/artstoryage/converter/ArtWorkConverter.java
> +  }
dto, converter,controller 중복되는 메서드 전부 수정했습니다.

2024-05-28 17:31 UTC, citycozy commented on src/main/java/com/example/artstoryage/domain/ArtWork.java
> +    auctionStartPrice = request.getBidPrice();
분리해서 수정했습니다.

2024-05-28 17:31 UTC, citycozy commented on src/main/java/com/example/artstoryage/service/impl/ArtWorkCommandServiceImpl.java
> +      throw new IllegalArgumentException("입찰가의 단위는 1만원입니다.");
수정했습니다.

2024-05-29 02:17 UTC, SIWON990327 approved these changes

2024-05-29 02:17 UTC, merged